# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'MapPart' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapPart
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'

  target 'MapPart-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  end

  target 'MapPartTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
